### ISSUE TITLE
conda install on py3.5 (OSX 10.9.5) doesn't work

### ISSUE THREAD

**Issue by andyfaff** [libdynd/dynd-python#582]
conda create -n pop dynd-python python=3
    source activate pop
    python
    >>> import dynd

Results in:

    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/Users/anz/miniconda3/envs/pop/lib/python3.5/site-packages/dynd/__init__.py", line 54, in <module>
    from .config import _dynd_version_string as __libdynd_version__, \
    ImportError: dlopen(/Users/anz/miniconda3/envs/pop/lib/python3.5/site-packages/dynd/config.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libpydynd.dylib
    Referenced from: /Users/anz/miniconda3/envs/pop/lib/python3.5/site-packages/dynd/config.cpython-35m-darwin.so
    Reason: image not found

**Comment by izaid** [comment]
Try conda install -c dynd/channel/dev dynd-python.
